import type {
  AtendimentoTicket,
  AtendimentoMessage,
  AtendimentoColumn,
  FlowStep,
  KBArticle,
  AISuggestion,
  TimelineEvent,
  HistoryTicket,
} from './types'

// ── Tickets ──────────────────────────────────────────────

export const mockTickets: AtendimentoTicket[] = [
  {
    id: 't-858',
    ticketNumber: 858,
    customerName: 'Tiago Da Costa Silva',
    customerPhone: '5528999831108',
    customerInitials: 'TC',
    subject: 'Erro ao Validar Licença Online - Bloqueio na assinatura',
    lastMessage: 'Salvou de ter que fechar a loja',
    lastMessageTime: '10:42',
    status: 'ag_cliente',
    priority: 'media',
    assignee: { id: 'h1', name: 'Agente Humano', initials: 'AH' },
    agent: { id: 'a1', name: 'Agente Suporte', type: 'ai' },
    unreadCount: 2,
    createdAt: '2026-03-14T08:30:00Z',
    updatedAt: '2026-03-16T10:42:00Z',
    channel: 'whatsapp',
    tags: ['Licença', 'Bloqueio'],
    module: 'Financeiro',
    category: 'Financeiro',
    sla: {
      firstResponse: { percentUsed: 30, status: 'ok', label: '12s' },
      resolution: { percentUsed: 85, status: 'warn', label: '20h 13m' },
    },
    client: {
      id: 'c1',
      name: 'Tiago Da Costa Silva',
      companyName: 'Mercearia Silva LTDA',
      cnpj: '12.345.678/0001-90',
      email: 'tiago@merceariasilva.com',
      phone: '5528999831108',
      product: 'GMS Pro',
      licenseStatus: 'Ativa',
    },
    aiConfidence: 72,
    sentiment: 'neutral',
    tempoFila: '20h 13m',
    messageCount: 23,
  },
  {
    id: 't-824',
    ticketNumber: 824,
    customerName: 'Douglas Ghion',
    customerPhone: '5511992877179',
    customerInitials: 'DG',
    subject: 'Aguardando retorno para resolução de problema',
    lastMessage: '[Áudio transcrito] Beleza Cleiton. Tudo tranquilo?',
    lastMessageTime: '09:15',
    status: 'ag_interno',
    priority: 'media',
    assignee: { id: 'h2', name: 'Katlyn', initials: 'KT' },
    agent: { id: 'a2', name: 'Katlyn', type: 'human' },
    unreadCount: 0,
    createdAt: '2026-03-12T14:00:00Z',
    updatedAt: '2026-03-16T09:15:00Z',
    channel: 'whatsapp',
    tags: ['Suporte', 'Retorno'],
    module: 'Suporte',
    category: 'Suporte',
    sla: {
      firstResponse: { percentUsed: 20, status: 'ok', label: '8s' },
      resolution: { percentUsed: 100, status: 'critical', label: '44h 15m' },
    },
    slaEstourado: true,
    client: {
      id: 'c2',
      name: 'Douglas Ghion',
      companyName: 'Tech Solutions ME',
      cnpj: '98.765.432/0001-10',
      email: 'douglas@techsolutions.com',
      phone: '5511992877179',
      product: 'GMS Basic',
      licenseStatus: 'Ativa',
    },
    aiConfidence: 45,
    sentiment: 'neutral',
    tempoAtendimento: '44h 15m',
    messageCount: 6,
  },
  {
    id: 't-662',
    ticketNumber: 662,
    customerName: 'Jessica Santos',
    customerPhone: '557781146457',
    customerInitials: 'JS',
    subject: 'Problema com cartão vinculado',
    lastMessage: 'É porque tá vinculado ao cartão. Eu quero saber...',
    lastMessageTime: '11:30',
    status: 'em_atendimento',
    priority: 'alta',
    assignee: { id: 'h3', name: 'Aline Martins', initials: 'AM' },
    agent: { id: 'a3', name: 'Aline Martins', type: 'human' },
    unreadCount: 3,
    createdAt: '2026-03-15T09:00:00Z',
    updatedAt: '2026-03-16T11:30:00Z',
    channel: 'whatsapp',
    tags: ['Cartão', 'Pagamento'],
    module: 'Suporte',
    category: 'Suporte',
    sla: {
      firstResponse: { percentUsed: 15, status: 'ok', label: '12s' },
      resolution: { percentUsed: 90, status: 'critical', label: '1d 2h' },
    },
    client: {
      id: 'c3',
      name: 'Jessica Santos',
      companyName: 'Loja Fashion JS',
      email: 'jessica@lojafashion.com',
      phone: '557781146457',
      product: 'GMS Pro',
      licenseStatus: 'Ativa',
    },
    aiConfidence: 88,
    sentiment: 'negative',
    messageCount: 8,
  },
  {
    id: 't-901',
    ticketNumber: 901,
    customerName: 'Carlos Mendes',
    customerPhone: '5521987654321',
    customerInitials: 'CM',
    subject: 'Dúvida sobre relatório financeiro',
    lastMessage: 'Como exporto o relatório mensal?',
    lastMessageTime: '11:55',
    status: 'fila',
    priority: 'baixa',
    unreadCount: 1,
    createdAt: '2026-03-16T11:50:00Z',
    updatedAt: '2026-03-16T11:55:00Z',
    channel: 'whatsapp',
    tags: ['Relatório', 'Dúvida'],
    module: 'Financeiro',
    category: 'Financeiro',
    sla: {
      firstResponse: { percentUsed: 10, status: 'ok', label: '5m' },
      resolution: { percentUsed: 5, status: 'ok', label: '5m' },
    },
    client: {
      id: 'c4',
      name: 'Carlos Mendes',
      companyName: 'Mendes & Cia',
      email: 'carlos@mendescia.com',
      phone: '5521987654321',
      product: 'GMS Enterprise',
      licenseStatus: 'Ativa',
    },
    aiConfidence: 95,
    sentiment: 'neutral',
    messageCount: 1,
  },
  {
    id: 't-899',
    ticketNumber: 899,
    customerName: 'Fernanda Lima',
    customerPhone: '5531998887766',
    customerInitials: 'FL',
    subject: 'Erro ao emitir nota fiscal eletrônica',
    lastMessage: 'Aparece "erro de comunicação com SEFAZ"',
    lastMessageTime: '11:40',
    status: 'fila',
    priority: 'alta',
    unreadCount: 4,
    createdAt: '2026-03-16T11:30:00Z',
    updatedAt: '2026-03-16T11:40:00Z',
    channel: 'whatsapp',
    tags: ['NF-e', 'SEFAZ', 'Erro'],
    module: 'Fiscal',
    category: 'Suporte',
    sla: {
      firstResponse: { percentUsed: 25, status: 'ok', label: '10m' },
      resolution: { percentUsed: 15, status: 'ok', label: '10m' },
    },
    client: {
      id: 'c5',
      name: 'Fernanda Lima',
      companyName: 'Papelaria Lima',
      email: 'fernanda@papelarialima.com',
      phone: '5531998887766',
      product: 'GMS Pro',
      licenseStatus: 'Ativa',
    },
    aiConfidence: 78,
    sentiment: 'negative',
    messageCount: 3,
  },
  {
    id: 't-880',
    ticketNumber: 880,
    customerName: 'Roberto Alves',
    customerPhone: '5541991234567',
    customerInitials: 'RA',
    subject: 'Integração com gateway de pagamento não funciona',
    lastMessage: 'Já tentei reconectar mas continua com erro',
    lastMessageTime: '08:20',
    status: 'em_atendimento',
    priority: 'urgente',
    assignee: { id: 'h4', name: 'Pedro Costa', initials: 'PC' },
    agent: { id: 'a4', name: 'Pedro Costa', type: 'human' },
    unreadCount: 0,
    createdAt: '2026-03-15T16:00:00Z',
    updatedAt: '2026-03-16T08:20:00Z',
    channel: 'whatsapp',
    tags: ['Integração', 'Pagamento', 'Gateway'],
    module: 'Integrações',
    category: 'Suporte',
    sla: {
      firstResponse: { percentUsed: 10, status: 'ok', label: '5s' },
      resolution: { percentUsed: 60, status: 'warn', label: '16h' },
    },
    client: {
      id: 'c6',
      name: 'Roberto Alves',
      companyName: 'Alves Comércio LTDA',
      email: 'roberto@alvescomercio.com',
      phone: '5541991234567',
      product: 'GMS Enterprise',
      licenseStatus: 'Ativa',
    },
    aiConfidence: 55,
    sentiment: 'negative',
    tempoAtendimento: '16h 20m',
    messageCount: 15,
  },
  {
    id: 't-850',
    ticketNumber: 850,
    customerName: 'Ana Paula Ribeiro',
    customerPhone: '5511955443322',
    customerInitials: 'AR',
    subject: 'Solicitação de nova funcionalidade no PDV',
    lastMessage: 'Seria possível adicionar leitura de código de barras?',
    lastMessageTime: '14:00',
    status: 'ag_cliente',
    priority: 'baixa',
    assignee: { id: 'h5', name: 'Marcos Silva', initials: 'MS' },
    agent: { id: 'a5', name: 'Agente Suporte', type: 'ai' },
    unreadCount: 0,
    createdAt: '2026-03-13T10:00:00Z',
    updatedAt: '2026-03-15T14:00:00Z',
    channel: 'whatsapp',
    tags: ['PDV', 'Feature Request'],
    module: 'PDV',
    category: 'Sugestão',
    sla: {
      firstResponse: { percentUsed: 5, status: 'ok', label: '3s' },
      resolution: { percentUsed: 40, status: 'ok', label: '2d 4h' },
    },
    client: {
      id: 'c7',
      name: 'Ana Paula Ribeiro',
      companyName: 'Mini Mercado Ribeiro',
      email: 'ana@minimercadoribeiro.com',
      phone: '5511955443322',
      product: 'GMS Basic',
      licenseStatus: 'Ativa',
    },
    aiConfidence: 90,
    sentiment: 'positive',
    messageCount: 4,
  },
  {
    id: 't-790',
    ticketNumber: 790,
    customerName: 'Luciana Torres',
    customerPhone: '5561988776655',
    customerInitials: 'LT',
    subject: 'Treinamento para equipe de vendas',
    lastMessage: 'Obrigada pelo material! Ficou excelente.',
    lastMessageTime: '16:30',
    status: 'concluido',
    priority: 'baixa',
    assignee: { id: 'h3', name: 'Aline Martins', initials: 'AM' },
    agent: { id: 'a3', name: 'Aline Martins', type: 'human' },
    unreadCount: 0,
    createdAt: '2026-03-10T09:00:00Z',
    updatedAt: '2026-03-14T16:30:00Z',
    channel: 'whatsapp',
    tags: ['Treinamento', 'Vendas'],
    module: 'Comercial',
    category: 'Treinamento',
    sla: {
      firstResponse: { percentUsed: 8, status: 'ok', label: '10s' },
      resolution: { percentUsed: 50, status: 'ok', label: '4d 7h' },
    },
    client: {
      id: 'c8',
      name: 'Luciana Torres',
      companyName: 'Torres Variedades',
      email: 'luciana@torresvariedades.com',
      phone: '5561988776655',
      product: 'GMS Pro',
      licenseStatus: 'Ativa',
    },
    aiConfidence: 92,
    sentiment: 'positive',
    messageCount: 12,
  },
  {
    id: 't-905',
    ticketNumber: 905,
    customerName: 'Paulo Henrique',
    customerPhone: '5571999887766',
    customerInitials: 'PH',
    subject: 'Sistema lento ao abrir cadastro de produtos',
    lastMessage: 'Demora mais de 30 segundos pra carregar',
    lastMessageTime: '12:05',
    status: 'fila',
    priority: 'media',
    unreadCount: 1,
    createdAt: '2026-03-16T12:00:00Z',
    updatedAt: '2026-03-16T12:05:00Z',
    channel: 'whatsapp',
    tags: ['Performance', 'Cadastro'],
    module: 'Produtos',
    category: 'Suporte',
    sla: {
      firstResponse: { percentUsed: 5, status: 'ok', label: '5m' },
      resolution: { percentUsed: 3, status: 'ok', label: '5m' },
    },
    aiConfidence: 82,
    sentiment: 'negative',
    messageCount: 2,
  },
  {
    id: 't-870',
    ticketNumber: 870,
    customerName: 'Mariana Costa',
    customerPhone: '5585977665544',
    customerInitials: 'MC',
    subject: 'Erro 500 ao gerar boleto bancário',
    lastMessage: 'O cliente está cobrando e eu não consigo emitir',
    lastMessageTime: '07:45',
    status: 'em_atendimento',
    priority: 'critica',
    assignee: { id: 'h1', name: 'Agente Humano', initials: 'AH' },
    agent: { id: 'a1', name: 'Agente Suporte', type: 'ai' },
    unreadCount: 5,
    createdAt: '2026-03-15T07:00:00Z',
    updatedAt: '2026-03-16T07:45:00Z',
    channel: 'whatsapp',
    tags: ['Boleto', 'Erro 500', 'Urgente'],
    module: 'Financeiro',
    category: 'Financeiro',
    sla: {
      firstResponse: { percentUsed: 5, status: 'ok', label: '3s' },
      resolution: { percentUsed: 75, status: 'warn', label: '24h 45m' },
    },
    client: {
      id: 'c10',
      name: 'Mariana Costa',
      companyName: 'MC Distribuidora',
      email: 'mariana@mcdistribuidora.com',
      phone: '5585977665544',
      product: 'GMS Enterprise',
      licenseStatus: 'Ativa',
    },
    aiConfidence: 65,
    sentiment: 'negative',
    tempoAtendimento: '24h 45m',
    messageCount: 18,
  },
  {
    id: 't-812',
    ticketNumber: 812,
    customerName: 'Ricardo Souza',
    customerPhone: '5548988776655',
    customerInitials: 'RS',
    subject: 'Configuração de backup automático',
    lastMessage: 'Resolvido! Backup configurado com sucesso.',
    lastMessageTime: '15:00',
    status: 'concluido',
    priority: 'media',
    assignee: { id: 'h4', name: 'Pedro Costa', initials: 'PC' },
    agent: { id: 'a4', name: 'Pedro Costa', type: 'human' },
    unreadCount: 0,
    createdAt: '2026-03-11T11:00:00Z',
    updatedAt: '2026-03-13T15:00:00Z',
    channel: 'whatsapp',
    tags: ['Backup', 'Configuração'],
    module: 'Infraestrutura',
    category: 'Suporte',
    sla: {
      firstResponse: { percentUsed: 10, status: 'ok', label: '8s' },
      resolution: { percentUsed: 35, status: 'ok', label: '2d 4h' },
    },
    aiConfidence: 88,
    sentiment: 'positive',
    messageCount: 9,
  },
  {
    id: 't-892',
    ticketNumber: 892,
    customerName: 'Beatriz Oliveira',
    customerPhone: '5527998765432',
    customerInitials: 'BO',
    subject: 'Migração de dados do sistema antigo',
    lastMessage: 'Quando ficará pronta a importação?',
    lastMessageTime: '10:00',
    status: 'ag_interno',
    priority: 'alta',
    assignee: { id: 'h5', name: 'Marcos Silva', initials: 'MS' },
    agent: { id: 'a5', name: 'Marcos Silva', type: 'human' },
    unreadCount: 1,
    createdAt: '2026-03-14T08:00:00Z',
    updatedAt: '2026-03-16T10:00:00Z',
    channel: 'whatsapp',
    tags: ['Migração', 'Dados', 'Importação'],
    module: 'Infraestrutura',
    category: 'Suporte',
    sla: {
      firstResponse: { percentUsed: 12, status: 'ok', label: '15s' },
      resolution: { percentUsed: 70, status: 'warn', label: '2d 2h' },
    },
    client: {
      id: 'c12',
      name: 'Beatriz Oliveira',
      companyName: 'Oliveira Confecções',
      email: 'beatriz@oliveiraconfeccoes.com',
      phone: '5527998765432',
      product: 'GMS Pro',
      licenseStatus: 'Ativa',
    },
    aiConfidence: 40,
    sentiment: 'neutral',
    tempoAtendimento: '2d 2h',
    messageCount: 7,
  },
]

// ── Mensagens ────────────────────────────────────────────

export const mockMessages: Record<string, AtendimentoMessage[]> = {
  't-858': [
    { id: 'm1', ticketId: 't-858', content: 'Bom dia! Estou com um problema na validação da licença online. O sistema está bloqueando minha assinatura.', sender: 'customer', senderName: 'Tiago', timestamp: '2026-03-14T08:30:00Z' },
    { id: 'm2', ticketId: 't-858', content: 'Olá Tiago! Vou verificar a situação da sua licença agora mesmo.', sender: 'ai', senderName: 'Agente Suporte', timestamp: '2026-03-14T08:30:12Z' },
    { id: 'm3', ticketId: 't-858', content: 'Identifiquei que houve uma falha na comunicação com o servidor de licenças. Vou escalar para o time técnico.', sender: 'ai', senderName: 'Agente Suporte', timestamp: '2026-03-14T08:31:00Z' },
    { id: 'm4', ticketId: 't-858', content: 'Ticket escalado para atendimento humano — confiança abaixo do threshold.', sender: 'system', timestamp: '2026-03-14T08:31:30Z' },
    { id: 'm5', ticketId: 't-858', content: 'Tiago, aqui é o suporte humano. Estou analisando o log do servidor de licenças.', sender: 'agent', senderName: 'Agente Humano', timestamp: '2026-03-14T09:00:00Z' },
    { id: 'm6', ticketId: 't-858', content: 'Encontrei o problema — havia um registro duplicado. Já corrigi. Pode tentar validar novamente?', sender: 'agent', senderName: 'Agente Humano', timestamp: '2026-03-14T10:15:00Z' },
    { id: 'm7', ticketId: 't-858', content: 'Funcionou! Salvou de ter que fechar a loja', sender: 'customer', senderName: 'Tiago', timestamp: '2026-03-16T10:42:00Z' },
  ],
  't-662': [
    { id: 'm10', ticketId: 't-662', content: 'Oi, tô com problema no cartão vinculado ao sistema. Não tá passando.', sender: 'customer', senderName: 'Jessica', timestamp: '2026-03-15T09:00:00Z' },
    { id: 'm11', ticketId: 't-662', content: 'Olá Jessica! Vou verificar a situação do cartão vinculado à sua conta.', sender: 'agent', senderName: 'Aline Martins', timestamp: '2026-03-15T09:00:12Z' },
    { id: 'm12', ticketId: 't-662', content: 'Verifiquei e o cartão cadastrado expirou mês passado. Precisa atualizar os dados.', sender: 'agent', senderName: 'Aline Martins', timestamp: '2026-03-15T09:05:00Z' },
    { id: 'm13', ticketId: 't-662', content: 'É porque tá vinculado ao cartão. Eu quero saber se posso trocar pra outro sem perder o plano.', sender: 'customer', senderName: 'Jessica', timestamp: '2026-03-16T11:30:00Z' },
  ],
  't-880': [
    { id: 'm20', ticketId: 't-880', content: 'A integração com o gateway de pagamento parou de funcionar desde ontem.', sender: 'customer', senderName: 'Roberto', timestamp: '2026-03-15T16:00:00Z' },
    { id: 'm21', ticketId: 't-880', content: 'Roberto, vamos verificar. Qual gateway você está utilizando?', sender: 'agent', senderName: 'Pedro Costa', timestamp: '2026-03-15T16:02:00Z' },
    { id: 'm22', ticketId: 't-880', content: 'PagSeguro. Já tentei reconectar mas continua com erro.', sender: 'customer', senderName: 'Roberto', timestamp: '2026-03-15T16:05:00Z' },
    { id: 'm23', ticketId: 't-880', content: 'Nota interna: Verificar se houve mudança na API do PagSeguro. Checando changelog.', sender: 'agent', senderName: 'Pedro Costa', timestamp: '2026-03-15T17:00:00Z', isInternal: true },
    { id: 'm24', ticketId: 't-880', content: 'Roberto, identificamos que o PagSeguro atualizou a API deles ontem. Estamos adaptando a integração.', sender: 'agent', senderName: 'Pedro Costa', timestamp: '2026-03-16T08:20:00Z' },
  ],
  't-870': [
    { id: 'm30', ticketId: 't-870', content: 'Bom dia! Urgente: não consigo gerar boleto. Aparece erro 500.', sender: 'customer', senderName: 'Mariana', timestamp: '2026-03-15T07:00:00Z' },
    { id: 'm31', ticketId: 't-870', content: 'Bom dia Mariana! Vou verificar imediatamente.', sender: 'ai', senderName: 'Agente Suporte', timestamp: '2026-03-15T07:00:03Z' },
    { id: 'm32', ticketId: 't-870', content: 'Escalando para atendimento prioritário — erro crítico no módulo financeiro.', sender: 'system', timestamp: '2026-03-15T07:00:30Z' },
    { id: 'm33', ticketId: 't-870', content: 'Mariana, já estou analisando. O erro está no serviço de geração de boletos.', sender: 'agent', senderName: 'Agente Humano', timestamp: '2026-03-15T07:15:00Z' },
    { id: 'm34', ticketId: 't-870', content: 'O cliente está cobrando e eu não consigo emitir', sender: 'customer', senderName: 'Mariana', timestamp: '2026-03-16T07:45:00Z' },
  ],
}

// Mensagem padrão para tickets sem conversas detalhadas
const defaultMessages = (ticket: AtendimentoTicket): AtendimentoMessage[] => [
  {
    id: `${ticket.id}-m1`,
    ticketId: ticket.id,
    content: ticket.lastMessage,
    sender: 'customer',
    senderName: ticket.customerName.split(' ')[0],
    timestamp: ticket.updatedAt,
  },
]

// ── Flow Steps ───────────────────────────────────────────

export const getFlowSteps = (status: string): FlowStep[] => {
  const steps: FlowStep[] = [
    { id: 'fila', label: 'Fila', status: 'pending' },
    { id: 'em_atendimento', label: 'Em Atendim.', status: 'pending' },
    { id: 'ag_cliente', label: 'Aguard. Cliente', status: 'pending' },
    { id: 'ag_interno', label: 'Aguard. Interno', status: 'pending' },
    { id: 'concluido', label: 'Concluído', status: 'pending' },
  ]

  const statusOrder = ['fila', 'em_atendimento', 'ag_cliente', 'ag_interno', 'concluido']
  const currentIdx = statusOrder.indexOf(status)

  return steps.map((step, i) => ({
    ...step,
    status: i < currentIdx ? 'done' : i === currentIdx ? 'current' : 'pending',
  }))
}

// ── Knowledge Base ───────────────────────────────────────

export const mockKBArticles: KBArticle[] = [
  { id: 'kb1', title: 'Como validar licença online', excerpt: 'Passo a passo para resolver problemas de validação de licença no sistema GMS.', relevance: 95, category: 'Licenciamento', tags: ['licença', 'validação'] },
  { id: 'kb2', title: 'Configuração de gateway de pagamento', excerpt: 'Guia completo para configurar PagSeguro, Mercado Pago e outros gateways.', relevance: 88, category: 'Integrações', tags: ['gateway', 'pagamento'] },
  { id: 'kb3', title: 'Resolução de erro 500 em boletos', excerpt: 'Procedimento para diagnosticar e resolver erros na geração de boletos bancários.', relevance: 82, category: 'Financeiro', tags: ['boleto', 'erro 500'] },
  { id: 'kb4', title: 'Migração de dados entre sistemas', excerpt: 'Tutorial de importação e exportação de dados para migração de sistema legado.', relevance: 75, category: 'Infraestrutura', tags: ['migração', 'dados'] },
  { id: 'kb5', title: 'Emissão de NF-e — Problemas com SEFAZ', excerpt: 'Soluções para erros de comunicação com SEFAZ na emissão de notas fiscais.', relevance: 70, category: 'Fiscal', tags: ['NF-e', 'SEFAZ'] },
]

// ── AI Suggestions ───────────────────────────────────────

export const mockAISuggestions: AISuggestion[] = [
  { id: 'ai1', content: 'Identifiquei que o problema está relacionado à expiração do certificado digital. Sugiro verificar a validade e renovar se necessário.', confidence: 92, source: 'RAG: Certificado Digital' },
  { id: 'ai2', content: 'Com base no histórico deste cliente, problemas similares foram resolvidos reiniciando o serviço de licenciamento no painel admin.', confidence: 85, source: 'Histórico de Tickets' },
  { id: 'ai3', content: 'Posso gerar um relatório detalhado do status da licença e enviar ao cliente para transparência.', confidence: 78, source: 'Ação Sugerida' },
]

// ── Timeline Events ──────────────────────────────────────

export const mockTimelineEvents: TimelineEvent[] = [
  { id: 'ev1', type: 'created', title: 'Ticket criado', description: 'Via WhatsApp — agente IA recebeu', timestamp: '2026-03-14T08:30:00Z', icon: 'sparkles', color: 'cyan' },
  { id: 'ev2', type: 'assigned', title: 'Atribuído a Agente Suporte (IA)', description: 'Orquestrador encaminhou para agente de suporte', timestamp: '2026-03-14T08:30:05Z', icon: 'bot', color: 'purple' },
  { id: 'ev3', type: 'stage_changed', title: 'Escalado para humano', description: 'Confiança abaixo do threshold (45%)', timestamp: '2026-03-14T08:31:30Z', icon: 'arrow-right', color: 'yellow' },
  { id: 'ev4', type: 'assigned', title: 'Atribuído a Agente Humano', timestamp: '2026-03-14T09:00:00Z', icon: 'user', color: 'navy' },
  { id: 'ev5', type: 'stage_changed', title: 'Aguardando Cliente', description: 'Correção aplicada, aguardando confirmação', timestamp: '2026-03-14T10:15:00Z', icon: 'clock', color: 'yellow' },
  { id: 'ev6', type: 'message', title: 'Cliente respondeu', description: '"Funcionou! Salvou de ter que fechar a loja"', timestamp: '2026-03-16T10:42:00Z', icon: 'message-square', color: 'green' },
]

// ── History Tickets ──────────────────────────────────────

export const mockHistoryTickets: HistoryTicket[] = [
  { id: 'ht1', ticketNumber: 682, subject: 'Dúvida sobre plano de assinatura', status: 'finalizado', date: '2026-03-11', aiSummary: 'Cliente questionou diferenças entre planos GMS Basic e Pro. Esclarecido e migrado para Pro.' },
  { id: 'ht2', ticketNumber: 550, subject: 'Erro ao sincronizar estoque', status: 'finalizado', date: '2026-02-22', aiSummary: 'Problema de sincronização entre PDV e estoque. Resolvido com atualização do módulo.' },
  { id: 'ht3', ticketNumber: 412, subject: 'Treinamento inicial do sistema', status: 'finalizado', date: '2026-01-15' },
]

// ── Helpers ──────────────────────────────────────────────

export function getTicketById(id: string): AtendimentoTicket | undefined {
  return mockTickets.find(t => t.id === id)
}

export function getMessagesForTicket(ticketId: string): AtendimentoMessage[] {
  return mockMessages[ticketId] || defaultMessages(mockTickets.find(t => t.id === ticketId)!)
}

export function getTicketsByStatus(status: string): AtendimentoTicket[] {
  return mockTickets.filter(t => t.status === status)
}

export function getColumns(): AtendimentoColumn[] {
  return [
    { id: 'fila', label: 'Fila', icon: 'inbox', color: 'var(--col-fila)', tickets: getTicketsByStatus('fila') },
    { id: 'em_atendimento', label: 'Em Atendimento', icon: 'headphones', color: 'var(--col-atendimento)', tickets: getTicketsByStatus('em_atendimento') },
    { id: 'ag_cliente', label: 'Aguardando Cliente', icon: 'clock', color: 'var(--col-ag-cliente)', tickets: getTicketsByStatus('ag_cliente') },
    { id: 'ag_interno', label: 'Aguardando Interno', icon: 'users', color: 'var(--col-ag-interno)', tickets: getTicketsByStatus('ag_interno') },
    { id: 'concluido', label: 'Concluído', icon: 'check-circle', color: 'var(--col-concluido)', tickets: getTicketsByStatus('concluido') },
  ]
}
