INSERT OR IGNORE INTO agents (id, name, division, emoji) VALUES
-- Existing 12 commands
('ai-agent-orchestrator', 'AI Agent Orchestrator', 'ai', '🤖'),
('ai-safety-guardrails', 'AI Safety Guardrails', 'ai', '🛡️'),
('ai-training-feedback-loop', 'AI Training Feedback', 'ai', '🔄'),
('automation-workflow-engine', 'Automation Workflow', 'automation', '⚙️'),
('conversation-flow-architect', 'Conversation Flow', 'ai', '💬'),
('crm-data-architect', 'CRM Data Architect', 'data', '🗄️'),
('otimizar-consumo', 'Otimizar Consumo', 'ops', '💰'),
('prompt-engineering-specialist', 'Prompt Engineering', 'ai', '✍️'),
('rag-knowledge-engineer', 'RAG Knowledge', 'ai', '📚'),
('sla-analytics-specialist', 'SLA Analytics', 'analytics', '📊'),
('supabase-realtime-engine', 'Supabase Realtime', 'infra', '⚡'),
('uazapi-specialist', 'UAZAPI Specialist', 'integration', '📱'),
-- New 14 from agency-agents
('code-reviewer', 'Code Reviewer', 'engineering', '👁️'),
('database-optimizer', 'Database Optimizer', 'engineering', '🗄️'),
('software-architect', 'Software Architect', 'engineering', '🏛️'),
('api-tester', 'API Tester', 'testing', '🔌'),
('performance-benchmarker', 'Performance Benchmarker', 'testing', '⚡'),
('workflow-optimizer', 'Workflow Optimizer', 'testing', '🔄'),
('evidence-collector', 'Evidence Collector', 'testing', '📸'),
('reality-checker', 'Reality Checker', 'testing', '🔍'),
('analytics-reporter', 'Analytics Reporter', 'support', '📊'),
('feedback-synthesizer', 'Feedback Synthesizer', 'product', '💬'),
('product-manager', 'Product Manager', 'product', '🧭'),
('senior-project-manager', 'Senior Project Manager', 'project', '👔'),
('agents-orchestrator', 'Agents Orchestrator', 'specialized', '🎭'),
('workflow-architect', 'Workflow Architect', 'specialized', '🗺️');
