// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pomueweeulenslxvsxar.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBvbXVld2VldWxlbnNseHZzeGFyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzA4MzI3OTksImV4cCI6MjA4NjQwODc5OX0.y_RJ9RJDB9d8oGiReG61s4Q_ji6xAcFK-RQepZNw0X8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});